### ISSUE TITLE
App Crashes after the third attempt to record

### ISSUE THREAD

**Issue by ximisoft** [saki4510t/ScreenRecordingSample#6]
Hi there,

I tried the app on my phone (Android 6), the first recording works fine, the second works but I can't preview the video. When I try to record for the third time app crashes.

Here is my logcat 

` android.media.MediaCodec$CodecException: Error 0xffffec77
                                                                                 at android.media.MediaCodec.native_configure(Native Method)
                                                                                 at android.media.MediaCodec.configure(MediaCodec.java:1778)
                                                                                 at com.ximisoft.screenrecorder.media.MediaVideoEncoderBase.prepare_surface_encoder(MediaVideoEncoderBase.java:73)
                                                                                 at com.ximisoft.screenrecorder.media.MediaScreenEncoder.prepare(MediaScreenEncoder.java:77)
                                                                                 at com.ximisoft.screenrecorder.media.MediaMuxerWrapper.prepare(MediaMuxerWrapper.java:76)
                                                                                 at com.ximisoft.screenrecorder.service.ScreenRecorderService.startScreenRecord(ScreenRecorderService.java:130)
                                                                                 at com.ximisoft.screenrecorder.service.ScreenRecorderService.onHandleIntent(ScreenRecorderService.java:90)
                                                                                 at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:158)
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)`

I tried to fix the issue but without success.

Anyone have the same issue?

**Comment by DeepteshVerma** [comment]
@ximisoft  I am having the same issue. [https://github.com/saki4510t/ScreenRecordingSample/issues/12](url)

How did you fix it?

**Comment by ximisoft** [comment]
Hi there, I did not fixed it, i just updated to the latest from repository and it seem be more stable but the issue is still present in many devices
